"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import { useState } from "react";
import Hider from "@/component/layout/hider";
import Login from "@/component/login";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLogin, setIsLogin] = useState(false);
  const [isSignup, setIsSignup] = useState(false);

  const handleLogin = () => {
    setIsLogin(true);
  };


  return (
    <html lang="en">
      <body className={inter.className}>
        <Hider />
        {isLogin ? children : <Login setLogin={handleLogin} />}
      </body>
    </html>
  );
}